import { validationList } from '../../../contants';

export const initialState = {
  fields: {
    id_agen: {
          name: 'id_agen',
          placeholder: 'Pilih Agen...',
          label: 'Nama Agen',
          type: 'select',
          inputType: '',
          validation: [validationList.required],
          value: null,
          error: null,
          options: [],
          isDisable: false,
      },
      parent_id: {
            name: 'parent_id',
            placeholder: 'Pilih Atasan...',
            label: 'Nama Atasan',
            type: 'select',
            inputType: '',
            validation: [],
            value: null,
            error: null,
            options: [],
            isDisable: true,
        },
      berlaku_mulai: {
            name: 'berlaku_mulai',
            placeholder: '',
            label: 'Mulai Berlaku',
            type: 'date',
            inputType: '',
            validation: [validationList.required],
            value: null,
            error: null,
            options: [],
            isDisable: false,
        },
      berlaku_akhir: {
          name: 'berlaku_akhir',
          placeholder: '',
          label: 'Akhir Berlaku',
          type: 'date',
          inputType: '',
          validation: [validationList.required],
          value: null,
          error: null,
          options: [],
          isDisable: false,
      },
      status: {
          name: 'status',
          placeholder: '',
          label: 'Status',
          type: 'check_box',
          validation: [],
          value: null,
          error: null,
          inputType: '',
          isDisable: false,
      },
  },
  alert: {
    show: false,
    message: '',
    error: false,
    success: false,
    showConfirm: false,
    onConfirm: () => {},
    confirmBtnText: 'OK',
    showCancel: false,
    onCancel: () => {},
    cancelBtnText: 'CANCEL',
  }
}